services:
  - type: web
    name: line-zh-th-translator-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: OPENAI_MODEL
        value: gpt-4.1-mini
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
